### ISSUE TITLE
Why `Semigroup a` in instance `Monoid (Maybe a)`?

### ISSUE THREAD

**Issue by dederer** [purescript/purescript-maybe#35]
instance monoidMaybe :: Semigroup a => Monoid (Maybe a) where
      mempty = Nothing

Should be:

    instance monoidMaybe :: Monoid a => Monoid (Maybe a) where
      mempty = Nothing

**Comment by garyb** [comment]
Strengthening the constraint that way makes the instance strictly less useful - what we have now means you can have a monoid for any semigroup by lifting it into `Maybe`.

I'm not sure why you'd want the latter instance at all, since it behaves the same as the current one but over-constraints the `a`.... I could perhaps understand:
``` purescript
instance monoidMaybe :: Monoid a => Monoid (Maybe a) where
  mempty = mempty
```
but that also doesn't seem as useful as the canonical `Maybe` instance.

**Comment by garyb** [comment]
See also https://www.reddit.com/r/haskell/comments/39tumu/make_semigroup_a_superclass_of_monoid/cs6hlca/

**Comment by dederer** [comment]
Now I understand, thank you.
