### ISSUE TITLE
MonadPlus instance for Maybe

### ISSUE THREAD

**Issue by Savelenko** [purescript/purescript-maybe#64]
Hi,

`MonadPlus` instance for `Maybe` is not provided. Either it is a simple omission not noticed up till now or I am missing something subtle. Happy to open a PR in the former case.

**Comment by garyb** [comment]
At one point `Maybe` wasn't a law-abiding `MonadPlus`. I took a look at various discussions about it (and the `Semigroup` behaviour for it, since it's supposed to match the `Alt`) to try figure out if it's currently valid or not, but it's not obvious to me what the situation is right now, so would need to double check that before adding the instance again.

**Comment by Savelenko** [comment]
I expected that it would be related to lawfulness. What is the difference between PureScript and Haskell approach to this particular case, given that in Haskell `Maybe` does have `MonadPlus`? Is it more strict formulation of expected laws and consistencies?

**Comment by garyb** [comment]
Dredged this one from my memory at last! We do have a different formulation of `MonadPlus` than in Haskell - we've gone through quite a bit of discussion and changes for things relating to the `MonadPlus` hierarchy, the most recently change being dropping `MonadZero` entirely - there's several threads with all the history of it in `purescript-control` :wink:.

In Haskell, `MonadPlus` is a bit looser, as instances satisfy either a distributive law like we have, or alternatively "Left Catch": https://wiki.haskell.org/MonadPlus

It seems a bit odd to allow either, as it means you can rely on neither if you're just abstracting with `MonadPlus`.
